export declare const e2eTestsConfig: {
    ETHEREUM_NETWORK_ID: number;
    ETHEREUM_RPC_URL: string;
    ETHEREUM_COLLECTION_ERC_721: string;
    ETHEREUM_COLLECTION_ERC_1155: string;
    ETHEREUM_WALLET_BUYER: string;
    TEZOS_WALLET_ENDPOINT: string;
    TEZOS_COLLECTION_ID_NFT: string;
    TEZOS_COLLECTION_ID_MT: string;
    TEZOS_WALLET_1: string;
    TEZOS_WALLET_2: string;
    TEZOS_WALLET_3: string;
    SOLANA_COLLECTION: string;
    SOLANA_URI: string;
    SOLANA_WALLET_1: number[];
    SOLANA_WALLET_2: number[];
    FLOW_RARIBLE_COLLECTION: string;
    FLOW_FT_CONTRACT_ADDRESS: string;
    FLOW_FUSD_CONTRACT_ADDRESS: string;
};
